import SwiftUI
import AppKit
import UniformTypeIdentifiers

struct TemplateStepView: View {
    @EnvironmentObject private var wizard: WizardState
    @EnvironmentObject private var ai: AIAssistant
    @State private var assistantPrompt = ""
    @State private var assistantPromptSourceBeatKey: String?
    @State private var assistantPromptIsAutoGenerated = true
    @State private var assistantSuggestion: String?
    @State private var assistantSuggestionBeatKey: String?
    @State private var isPrompting = false
    @State private var isBuildingOutline = false
    @State private var outlineExpansionProgress: String?
    @State private var isDraftingBeat = false
    @State private var activeAIActionID: UUID?
    @State private var activeAITask: Task<Void, Never>?
    @State private var selectedBeatKey: String = ""
    @State private var activeBeatId: String?  // Track which beat is currently being edited inline
    @State private var beatElement: BeatElement = .card
    @State private var includeGuidance = true
    @State private var storyOutline: [String: String] = [:]
    @State private var storyOutlineError: String?
    @State private var exportStatusMessage: String?
    @State private var exportStatusIsError = false
    @State private var showSampleAlertFlag = false

    private var filledCount: Int {
        wizard.beats.filter { !(wizard.entries[$0.key]?.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty ?? true) }.count
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 24) {
            HStack(alignment: .top, spacing: 16) {
                heading
                Spacer(minLength: 16)
                beatsExportMenu
            }
            progressBar

            ForEach(actGroups, id: \.act) { group in
                VStack(alignment: .leading, spacing: 14) {
                    Text(group.label)
                        .font(.title3.weight(.bold))
                        .foregroundStyle(.tint)
                        .padding(.top, 4)
                    ForEach(group.beats) { beat in
                        BeatLineView(
                            beat: beat,
                            isActive: activeBeatId == beat.id,
                            onFocus: { activeBeatId = beat.id }
                        )
                    }
                }
            }

            continueToScenesPanel

            if let exportStatusMessage {
                Text(exportStatusMessage)
                    .font(.callout.weight(.medium))
                    .foregroundStyle(exportStatusIsError ? .red : .secondary)
            }
        }
        .onAppear { 
            syncSelectedBeat()
        }
        .onChange(of: wizard.beats.map(\.key)) { _, _ in syncSelectedBeat() }
        .onChange(of: selectedBeatKey) { _, _ in syncAssistantPrompt() }
        // Note: Sample Beat References alert removed in v3.0b24 - no sample selection step
    }

    // MARK: Heading

    private var heading: some View {
        VStack(alignment: .leading, spacing: 16) {
            VStack(alignment: .leading, spacing: 6) {
                Text("YOUR TEMPLATE")
                    .font(.caption.weight(.semibold))
                    .foregroundStyle(.tint)
                    .tracking(1.2)
                Text(wizard.projectTitle.isEmpty ? "Untitled" : wizard.projectTitle)
                    .font(.system(size: 30, weight: .bold, design: .rounded))
                metaLine
            }
            if !wizard.logline.isEmpty {
                Text(wizard.logline)
                    .font(.title3)
                    .italic()
                    .foregroundStyle(.secondary)
            }
        }
    }

    private var beatsExportMenu: some View {
        Menu {
            Button {
                exportBeatsToFinalDraft(openAfterWrite: true)
            } label: {
                Label("Open in Final Draft", systemImage: "arrow.up.forward.app")
            }

            Button {
                exportBeatsToFinalDraft(openAfterWrite: false)
            } label: {
                Label("Save .fdx…", systemImage: "square.and.arrow.down")
            }
        } label: {
            Label("Export", systemImage: "film.stack")
        }
        .menuStyle(.borderlessButton)
        .buttonStyle(.borderedProminent)
    }

    private var metaLine: some View {
        HStack(spacing: 6) {
            if let s = wizard.structure { Text(s.title) }
            if let m = wizard.medium, let r = wizard.runtime {
                Text("·"); Text("\(m.rawValue) · \(r.label)")
            }
            if !wizard.selectedGenres.isEmpty { let genreList = wizard.selectedGenres.joined(separator: ", "); Text("·"); Text(genreList) }
        }
        .font(.callout)
        .foregroundStyle(.secondary)
    }

    private var assistantPromptPanel: some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack(alignment: .firstTextBaseline) {
                VStack(alignment: .leading, spacing: 4) {
                    Text("AI Assistant")
                        .font(.headline)
                    Text("Choose a beat, then ask for a draft, rewrite, or notes.")
                        .font(.callout)
                        .foregroundStyle(.secondary)
                }
                Spacer()
                if !ai.isConfigured {
                    Text("Connect a local LLM in the AI menu")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }
            }

            if let beat = selectedBeat {
                HStack(spacing: 8) {
                    Image(systemName: "target")
                        .font(.caption.weight(.semibold))
                    Text("Targeting")
                        .font(.caption.weight(.semibold))
                    Text(beat.title)
                        .font(.caption)
                    Spacer()
                    Text(beat.actLabel)
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }
                .padding(.horizontal, 12)
                .padding(.vertical, 8)
                .background(
                    RoundedRectangle(cornerRadius: 10, style: .continuous)
                        .fill(Color.accentColor.opacity(0.08)))
            }

            Picker("Target beat", selection: selectedBeatSelection) {
                ForEach(wizard.beats) { beat in
                    Text(beat.title).tag(beat.key)
                }
            }
            .pickerStyle(.menu)

            ZStack(alignment: .topLeading) {
                TextEditor(text: $assistantPrompt)
                    .font(.body)
                    .frame(minHeight: 88)
                    .padding(8)
                    .background(
                        RoundedRectangle(cornerRadius: 10)
                            .fill(Color(nsColor: .textBackgroundColor)))
                    .overlay(
                        RoundedRectangle(cornerRadius: 10)
                            .strokeBorder(Color.primary.opacity(0.1)))
                if assistantPrompt.isEmpty {
                    Text("Ask something like: \"How can I raise the stakes in the midpoint?\"")
                        .foregroundStyle(.secondary)
                        .padding(16)
                        .allowsHitTesting(false)
                }
            }

            HStack(spacing: 10) {
                Button {
                    startAIAction { await askAssistant() }
                } label: {
                    if isPrompting {
                        HStack(spacing: 6) {
                            ProgressView().controlSize(.small)
                            Text("Asking…")
                        }
                    } else {
                        Label("Ask AI", systemImage: "sparkles")
                    }
                }
                .buttonStyle(.borderedProminent)
                .disabled(isPrompting || assistantPrompt.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty || !ai.isConfigured || selectedBeat == nil)

                Button {
                    startAIAction { await draftSelectedBeat() }
                } label: {
                    if isPrompting {
                        HStack(spacing: 6) {
                            ProgressView().controlSize(.small)
                            Text("Drafting…")
                        }
                    } else {
                        Label("Draft Beat", systemImage: "sparkles")
                    }
                }
                .buttonStyle(.bordered)
                .disabled(isPrompting || !ai.isConfigured || selectedBeat == nil)

                if activeAIActionID != nil {
                    Button("Cancel AI") {
                        cancelAIAction()
                    }
                    .buttonStyle(.bordered)
                }

                Button("Clear") {
                    assistantPrompt = ""
                    clearSuggestion()
                }
                .disabled(isPrompting)

                Spacer()
            }

            if let assistantSuggestion,
               let suggestionBeat = selectedBeat,
               assistantSuggestionBeatKey == suggestionBeat.key {
                VStack(alignment: .leading, spacing: 10) {
                    HStack {
                        Text("AI suggestion")
                            .font(.headline)
                        Spacer()
                        Text(suggestionBeat.title)
                            .font(.caption)
                            .foregroundStyle(.secondary)
                        Button {
                            copyToClipboard(assistantSuggestion)
                        } label: {
                            Label("Copy", systemImage: "doc.on.doc")
                        }
                        .buttonStyle(.borderless)
                    }

                    Text(assistantSuggestion)
                        .font(.callout)
                        .fixedSize(horizontal: false, vertical: true)
                        .textSelection(.enabled)

                    HStack {
                        Button {
                            useSuggestion()
                        } label: {
                            Label("Use suggestion", systemImage: "arrow.down.doc")
                        }
                        .buttonStyle(.borderedProminent)

                        Button("Dismiss") {
                            clearSuggestion()
                        }
                        .buttonStyle(.bordered)

                        Spacer()
                    }
                }
                .padding(14)
                .frame(maxWidth: .infinity, alignment: .leading)
                .background(
                    RoundedRectangle(cornerRadius: 12, style: .continuous)
                        .fill(Color(nsColor: .controlBackgroundColor)))
                .overlay(
                    RoundedRectangle(cornerRadius: 12, style: .continuous)
                        .strokeBorder(Color.primary.opacity(0.08)))
            }
        }
        .padding(18)
        .background(
            RoundedRectangle(cornerRadius: 14, style: .continuous)
                .fill(Color(nsColor: .controlBackgroundColor)))
        .overlay(
            RoundedRectangle(cornerRadius: 14, style: .continuous)
                .strokeBorder(Color.primary.opacity(0.08)))
    }

    private var storyOutlinePanel: some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack(alignment: .firstTextBaseline) {
                VStack(alignment: .leading, spacing: 4) {
                    Text("Story Outline")
                        .font(.headline)
                    Text("Generate a full outline, then insert individual beats or apply the whole pass.")
                        .font(.callout)
                        .foregroundStyle(.secondary)
                }
                Spacer()
                if !ai.isConfigured {
                    Text("Connect a local LLM in the AI menu")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }
            }

            HStack(spacing: 10) {
                Button {
                    startAIAction { await buildStoryOutline() }
                } label: {
                    if isBuildingOutline {
                        HStack(spacing: 6) {
                            ProgressView().controlSize(.small)
                            Text(outlineButtonLabel)
                        }
                    } else {
                        Label("Create Story Outline", systemImage: "list.bullet.rectangle")
                    }
                }
                .buttonStyle(.borderedProminent)
                .disabled(isBuildingOutline || !ai.isConfigured)

                if activeAIActionID != nil {
                    Button("Cancel AI") {
                        cancelAIAction()
                    }
                    .buttonStyle(.bordered)
                }

                Button("Clear Outline") {
                    clearStoryOutline()
                }
                .buttonStyle(.bordered)
                .disabled(storyOutline.isEmpty && storyOutlineError == nil)

                Spacer()
            }

            outlinePreview
        }
        .padding(18)
        .background(
            RoundedRectangle(cornerRadius: 14, style: .continuous)
                .fill(Color(nsColor: .controlBackgroundColor)))
        .overlay(
            RoundedRectangle(cornerRadius: 14, style: .continuous)
                .strokeBorder(Color.primary.opacity(0.08)))
    }

    private var progressBar: some View {
        VStack(alignment: .leading, spacing: 6) {
            HStack {
                Text("\(filledCount) of \(wizard.beats.count) beats written")
                    .font(.caption.weight(.medium))
                    .foregroundStyle(.secondary)
                Spacer()
            }
            GeometryReader { geo in
                ZStack(alignment: .leading) {
                    Capsule().fill(Color.secondary.opacity(0.18))
                    Capsule().fill(Color.accentColor)
                        .frame(width: geo.size.width * progressFraction)
                }
            }
            .frame(height: 8)
        }
    }

    private var progressFraction: CGFloat {
        guard !wizard.beats.isEmpty else { return 0 }
        return CGFloat(filledCount) / CGFloat(wizard.beats.count)
    }

    // MARK: Grouping

    private struct ActGroup { let act: Int; let label: String; let beats: [BeatTemplate] }

    private var actGroups: [ActGroup] {
        var groups: [ActGroup] = []
        for beat in wizard.beats {
            if let idx = groups.firstIndex(where: { $0.act == beat.act }) {
                groups[idx] = ActGroup(act: beat.act, label: groups[idx].label, beats: groups[idx].beats + [beat])
            } else {
                groups.append(ActGroup(act: beat.act, label: beat.actLabel, beats: [beat]))
            }
        }
        return groups
    }

    // MARK: Actions

    private func copyToClipboard(_ text: String) {
        let pb = NSPasteboard.general
        pb.clearContents()
        pb.setString(text, forType: .string)
    }

    @MainActor
    private func draftSelectedBeat() async {
        guard let beat = selectedBeat else { return }
        if let result = await ai.draftBeat(beat, wizard: wizard) {
            wizard.entries[beat.key] = result
            selectedBeatKey = beat.key
            clearStoryOutline()
        }
    }

    @MainActor
    private func buildStoryOutline() async {
        isBuildingOutline = true
        storyOutlineError = nil
        outlineExpansionProgress = "Drafting quick outline..."
        defer { isBuildingOutline = false }

        do {
            let quickOutline = try await ai.createStoryOutline(wizard: wizard)
            storyOutline = quickOutline

            if let firstBeat = wizard.beats.first(where: { quickOutline[$0.key] != nil }) {
                selectedBeatKey = firstBeat.key
            }

            let outlineBeats = wizard.beats.compactMap { quickOutline[$0.key] != nil ? $0 : nil }
            for (index, beat) in outlineBeats.enumerated() {
                guard let quickLine = quickOutline[beat.key] else { continue }
                if Task.isCancelled { throw CancellationError() }

                outlineExpansionProgress = "Expanding beat \(index + 1) of \(outlineBeats.count): \(beat.title)"

                if let expanded = await ai.expandBeatOutline(quickLine, beat: beat, wizard: wizard) {
                    let cleaned = expanded.trimmingCharacters(in: .whitespacesAndNewlines)
                    guard !cleaned.isEmpty else { continue }
                    storyOutline[beat.key] = cleaned
                    wizard.entries[beat.key] = cleaned
                }
            }

            if let firstBeat = wizard.beats.first(where: { storyOutline[$0.key] != nil }) {
                selectedBeatKey = firstBeat.key
            }
            outlineExpansionProgress = "Finished expanding \(storyOutline.count) beats."
        } catch is CancellationError {
            outlineExpansionProgress = nil
            return
        }
        catch {
            storyOutlineError = error.localizedDescription
            outlineExpansionProgress = nil
        }
    }

    @MainActor
    private func askAssistant() async {
        let prompt = assistantPrompt.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !prompt.isEmpty else { return }
        guard let beat = selectedBeat else { return }
        isPrompting = true
        defer { isPrompting = false }

        if let result = await ai.answerPrompt(prompt, beat: beat, wizard: wizard) {
            assistantSuggestion = result
            assistantSuggestionBeatKey = beat.key
        }
    }

    private var selectedBeat: BeatTemplate? {
        wizard.beats.first(where: { $0.key == selectedBeatKey }) ?? wizard.beats.first
    }

    private var selectedBeatSelection: Binding<String> {
        Binding(
            get: { selectedBeatKey.isEmpty ? (wizard.beats.first?.key ?? "") : selectedBeatKey },
            set: { selectedBeatKey = $0 }
        )
    }

    // Sample movie functionality removed in v3.0b24

    private func syncSelectedBeat() {
        guard let first = wizard.beats.first else {
            selectedBeatKey = ""
            return
        }
        if wizard.beats.contains(where: { $0.key == selectedBeatKey }) {
            syncAssistantPrompt()
            return
        }
        selectedBeatKey = first.key
    }

    private func syncAssistantPrompt() {
        guard let beat = selectedBeat else {
            assistantPrompt = ""
            assistantPromptSourceBeatKey = nil
            assistantPromptIsAutoGenerated = true
            clearSuggestion()
            return
        }

        let generated = autoPrompt(for: beat)
        if assistantPrompt.isEmpty || assistantPromptIsAutoGenerated || assistantPromptSourceBeatKey != beat.key {
            assistantPrompt = generated
            assistantPromptSourceBeatKey = beat.key
            assistantPromptIsAutoGenerated = true
            clearSuggestion()
        }
    }

    private func autoPrompt(for beat: BeatTemplate) -> String {
        let draft = currentDraftText(for: beat)
        let draftAction = draft.isEmpty
            ? "Draft this beat from scratch."
            : "Rewrite this beat to make it sharper and more dramatic."
        let timing = wizard.runtime.map { beat.timing(for: $0) } ?? "Unknown"

        return """
        Beat Brief
        Title: \(beat.title)
        Act: \(beat.actLabel)
        Timing: \(timing)

        Purpose:
        \(beat.purpose)

        Current Draft:
        \(draft.isEmpty ? "No draft yet." : draft)

        Request:
        \(draftAction)
        """
    }

    private func currentDraftText(for beat: BeatTemplate) -> String {
        wizard.entries[beat.key]?
            .trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
    }

    private func useSuggestion() {
        guard let beat = selectedBeat, let assistantSuggestion else { return }
        let current = currentDraftText(for: beat)
        let merged = mergeDraft(current: current, suggestion: assistantSuggestion)
        wizard.entries[beat.key] = merged
        clearSuggestion()
        syncAssistantPrompt()
    }

    private func mergeDraft(current: String, suggestion: String) -> String {
        let currentSentences = sentenceList(from: current)
        let suggestionSentences = sentenceList(from: suggestion)

        guard !currentSentences.isEmpty else { return suggestion.trimmingCharacters(in: .whitespacesAndNewlines) }
        guard !suggestionSentences.isEmpty else { return current.trimmingCharacters(in: .whitespacesAndNewlines) }

        let count = max(currentSentences.count, suggestionSentences.count)
        var merged: [String] = []
        for index in 0..<count {
            let original = index < currentSentences.count ? currentSentences[index] : nil
            let rewritten = index < suggestionSentences.count ? suggestionSentences[index] : nil

            switch (original, rewritten) {
            case let (_, rewritten?):
                merged.append(rewritten)
            case let (original?, nil):
                merged.append(original)
            case (nil, nil):
                break
            }
        }
        return merged.joined(separator: " ")
    }

    private func sentenceList(from text: String) -> [String] {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return [] }

        let nsText = trimmed as NSString
        var sentences: [String] = []
        nsText.enumerateSubstrings(
            in: NSRange(location: 0, length: nsText.length),
            options: [.bySentences, .substringNotRequired]
        ) { _, range, _, _ in
            let sentence = nsText.substring(with: range).trimmingCharacters(in: .whitespacesAndNewlines)
            if !sentence.isEmpty {
                sentences.append(sentence)
            }
        }
        return sentences.isEmpty ? [trimmed] : sentences
    }

    private func clearSuggestion() {
        assistantSuggestion = nil
        assistantSuggestionBeatKey = nil
    }

    private var outlinePreview: some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack(alignment: .firstTextBaseline) {
                VStack(alignment: .leading, spacing: 4) {
                    Text("Outline Draft")
                        .font(.headline)
                    Text("Insert each generated piece into the matching beat, or apply all at once.")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                    if let outlineExpansionProgress {
                        Text(outlineExpansionProgress)
                            .font(.caption.weight(.medium))
                            .foregroundStyle(.secondary)
                    }
                }
                Spacer()
                if isBuildingOutline {
                    ProgressView()
                        .controlSize(.small)
                }
                Button("Insert All") {
                    applyOutlineToAllBeats()
                }
                .buttonStyle(.borderedProminent)
                .disabled(storyOutline.isEmpty)
            }

            if let storyOutlineError {
                Text(storyOutlineError)
                    .font(.caption)
                    .foregroundStyle(.orange)
            }

            if storyOutline.isEmpty {
                Text("No outline yet. Create one above to see beat-by-beat inserts here.")
                    .font(.callout)
                    .foregroundStyle(.secondary)
                    .padding(.vertical, 4)
            } else {
                VStack(alignment: .leading, spacing: 10) {
                    ForEach(wizard.beats.filter { storyOutline[$0.key] != nil }) { beat in
                        if let text = storyOutline[beat.key] {
                            outlineBeatRow(beat: beat, text: text)
                        }
                    }
                }
            }
        }
        .padding(14)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(
            RoundedRectangle(cornerRadius: 12, style: .continuous)
                .fill(Color(nsColor: .controlBackgroundColor)))
        .overlay(
            RoundedRectangle(cornerRadius: 12, style: .continuous)
                .strokeBorder(Color.primary.opacity(0.08)))
    }

    private var continueToScenesPanel: some View {
        VStack(alignment: .leading, spacing: 12) {
            Text("Ready for scenes?")
                .font(.headline)
            Text("Move into Scenes when the beats are set to split each beat into editable scenes.")
                .font(.caption)
                .foregroundStyle(.secondary)
            Button {
                wizard.next()
            } label: {
                Label("Continue to Scenes", systemImage: "arrow.right")
            }
            .buttonStyle(.borderedProminent)
            .disabled(wizard.beats.isEmpty)
        }
        .padding(16)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(
            RoundedRectangle(cornerRadius: 14, style: .continuous)
                .fill(Color(nsColor: .controlBackgroundColor)))
        .overlay(
            RoundedRectangle(cornerRadius: 14, style: .continuous)
                .strokeBorder(Color.primary.opacity(0.08)))
    }

    private func exportBeatsToFinalDraft(openAfterWrite: Bool) {
        let panel = NSSavePanel()
        if let fdxType = UTType(filenameExtension: "fdx") {
            panel.allowedContentTypes = [fdxType]
        }

        let safeTitle = wizard.projectTitle.isEmpty ? "CreateIT Beats" : "\(wizard.projectTitle) Beats"
        panel.nameFieldStringValue = "\(safeTitle).fdx"
        panel.canCreateDirectories = true
        panel.allowsOtherFileTypes = false
        panel.treatsFilePackagesAsDirectories = false
        panel.isExtensionHidden = false

        guard panel.runModal() == .OK, let url = panel.url else { return }

        let fdx = FDXExporter.export(
            from: wizard,
            beatElement: beatElement,
            includeGuidance: includeGuidance,
            includeSceneScript: false)

        do {
            try fdx.write(to: url, atomically: true, encoding: .utf8)
            if openAfterWrite {
                NSWorkspace.shared.open(url)
            exportStatusMessage = "Opened \(url.lastPathComponent) in Final Draft."
        } else {
                exportStatusMessage = "Saved \(url.lastPathComponent)."
            }
            exportStatusIsError = false
        } catch {
            exportStatusMessage = error.localizedDescription
            exportStatusIsError = true
        }
    }

    private func outlineBeatRow(beat: BeatTemplate, text: String) -> some View {
        VStack(alignment: .leading, spacing: 8) {
            HStack {
                VStack(alignment: .leading, spacing: 2) {
                    Text(beat.title)
                        .font(.headline)
                    Text(beat.key)
                        .font(.caption.monospaced())
                        .foregroundStyle(.secondary)
                }
                Spacer()
                Button("Insert") {
                    wizard.entries[beat.key] = text
                    selectedBeatKey = beat.key
                    clearSuggestion()
                }
                .buttonStyle(.borderedProminent)
            }
            Text(text)
                .font(.callout)
                .foregroundStyle(.primary)
                .fixedSize(horizontal: false, vertical: true)
                .textSelection(.enabled)
        }
        .padding(12)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(
            RoundedRectangle(cornerRadius: 10, style: .continuous)
                .fill(Color.accentColor.opacity(0.06)))
    }

    private func applyOutlineToAllBeats() {
        for beat in wizard.beats {
            if let text = storyOutline[beat.key] {
                wizard.entries[beat.key] = text
            }
        }
        if let firstBeat = wizard.beats.first(where: { storyOutline[$0.key] != nil }) {
            selectedBeatKey = firstBeat.key
        }
        clearSuggestion()
    }

    private func clearStoryOutline() {
        storyOutline = [:]
        storyOutlineError = nil
        outlineExpansionProgress = nil
    }

    private func startAIAction(_ operation: @escaping @Sendable () async -> Void) {
        cancelAIAction()
        let actionID = UUID()
        activeAIActionID = actionID
        activeAITask = Task {
            await operation()
            await MainActor.run {
                if activeAIActionID == actionID {
                    activeAIActionID = nil
                    activeAITask = nil
                }
            }
        }
    }

    private func cancelAIAction() {
        activeAITask?.cancel()
        activeAITask = nil
        activeAIActionID = nil
        isPrompting = false
        isBuildingOutline = false
        outlineExpansionProgress = nil
    }

    private var outlineButtonLabel: String {
        outlineExpansionProgress ?? "Creating..."
    }

    @MainActor
    private func draftBeatWithAI(_ beat: BeatTemplate) async -> Bool {
        guard let result = await ai.draftBeat(beat, wizard: wizard) else { return false }
        wizard.entries[beat.key] = result
        selectedBeatKey = beat.key
        return true
    }
}

// MARK: - Beat Card

struct BeatCardView: View {
    @EnvironmentObject private var wizard: WizardState
    @EnvironmentObject private var ai: AIAssistant
    let beat: BeatTemplate
    let isTargeted: Bool
    let onFocus: () -> Void
    let onDraftWithAI: () -> Void
    @State private var showSample = true

    private var isGenerating: Bool { ai.generating.contains(beat.key) }

    private var binding: Binding<String> {
        Binding(
            get: { wizard.entries[beat.key] ?? "" },
            set: { wizard.entries[beat.key] = $0 }
        )
    }

    // Sample movie functionality removed in v3.0b24

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            header
            Text(beat.purpose)
                .font(.callout)
                .foregroundStyle(.secondary)
                .fixedSize(horizontal: false, vertical: true)

            ZStack(alignment: .topLeading) {
                BeatDraftTextEditor(text: binding) {
                    onFocus()
                }
                    .frame(minHeight: 90)
                    .background(
                        RoundedRectangle(cornerRadius: 10)
                            .fill(Color(nsColor: .textBackgroundColor)))
                    .overlay(
                        RoundedRectangle(cornerRadius: 10)
                            .strokeBorder(Color.primary.opacity(0.1)))
                    .onChange(of: binding.wrappedValue) { _, _ in onFocus() }
                if binding.wrappedValue.isEmpty {
                    Text(beat.placeholder)
                        .foregroundStyle(.secondary)
                        .padding(16)
                        .allowsHitTesting(false)
                }
            }
            .contentShape(RoundedRectangle(cornerRadius: 10, style: .continuous))
            .simultaneousGesture(TapGesture().onEnded {
                onFocus()
            })
            .onAppear {
                if isTargeted { onFocus() }
            }

            HStack(spacing: 10) {
                Button {
                    onDraftWithAI()
                } label: {
                    if isGenerating {
                        HStack(spacing: 6) {
                            ProgressView().controlSize(.small)
                            Text("Writing…")
                        }
                    } else {
                        Label(binding.wrappedValue.isEmpty ? "Draft with AI" : "Rewrite with AI",
                              systemImage: "sparkles")
                    }
                }
                .disabled(isGenerating || !ai.isConfigured)
                .controlSize(.small)

                if !ai.isConfigured {
                    Text("Connect a local LLM in the AI menu")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }
                Spacer()
            }
        }
        .padding(18)
        .background(
            RoundedRectangle(cornerRadius: 14, style: .continuous)
                .fill(isTargeted ? Color.accentColor.opacity(0.16) : Color(nsColor: .controlBackgroundColor)))
        .overlay(
            RoundedRectangle(cornerRadius: 14, style: .continuous)
                .strokeBorder(isTargeted ? Color.accentColor : Color.primary.opacity(0.08), lineWidth: isTargeted ? 3 : 1))
        .contentShape(RoundedRectangle(cornerRadius: 14, style: .continuous))
        .simultaneousGesture(TapGesture().onEnded {
            onFocus()
        })
    }

    private var header: some View {
        HStack(alignment: .firstTextBaseline) {
            Text(beat.title)
                .font(.title3.weight(.bold))
            if isTargeted {
                Text("AI target")
                    .font(.caption.weight(.semibold))
                    .padding(.horizontal, 8)
                    .padding(.vertical, 3)
                    .background(Capsule().fill(Color.accentColor.opacity(0.14)))
                    .foregroundStyle(.tint)
            }
            Spacer()
            if let runtime = wizard.runtime {
                Text(beat.timing(for: runtime))
                    .font(.caption.weight(.medium))
                    .foregroundStyle(.secondary)
                    .padding(.horizontal, 8)
                    .padding(.vertical, 3)
                    .background(Capsule().fill(Color.secondary.opacity(0.12)))
            }
        }
    }

    private func sampleBox(_ text: String) -> some View {
        VStack(alignment: .leading, spacing: 4) {
            HStack(spacing: 6) {
                Image(systemName: "lightbulb")
                    .font(.caption)
                Text("Reference example for this beat")
                    .font(.caption.weight(.semibold))
                Spacer()
                Button(showSample ? "Hide" : "Show") {
                    withAnimation { showSample.toggle() }
                }
                .buttonStyle(.plain)
                .font(.caption)
                .foregroundStyle(.tint)
            }
            .foregroundStyle(.tint)

            if showSample {
                Text(text)
                    .font(.callout)
                    .italic()
                    .fixedSize(horizontal: false, vertical: true)
                    .foregroundStyle(.primary.opacity(0.85))
            }
        }
        .padding(12)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(
            RoundedRectangle(cornerRadius: 10)
                .fill(Color.accentColor.opacity(0.08)))
        .overlay(
            RoundedRectangle(cornerRadius: 10)
                .strokeBorder(Color.accentColor.opacity(0.2)))
    }

}

private struct BeatDraftTextEditor: NSViewRepresentable {
    @Binding var text: String
    var onFocus: () -> Void

    func makeCoordinator() -> Coordinator {
        Coordinator(text: $text, onFocus: onFocus)
    }

    func makeNSView(context: Context) -> NSScrollView {
        let scrollView = BeatEditorScrollView()
        scrollView.onActivate = onFocus
        scrollView.drawsBackground = false
        scrollView.hasVerticalScroller = true
        scrollView.hasHorizontalScroller = false
        scrollView.autohidesScrollers = true
        scrollView.borderType = .noBorder
        scrollView.backgroundColor = .clear
        scrollView.focusRingType = .none

        let textView = BeatEditorTextView()
        textView.onActivate = onFocus
        textView.delegate = context.coordinator
        textView.isRichText = false
        textView.importsGraphics = false
        textView.isEditable = true
        textView.isSelectable = true
        textView.allowsUndo = true
        textView.isVerticallyResizable = true
        textView.isHorizontallyResizable = false
        textView.autoresizingMask = [.width]
        textView.textContainerInset = NSSize(width: 8, height: 8)
        textView.textContainer?.widthTracksTextView = true
        textView.textContainer?.containerSize = NSSize(width: 0, height: CGFloat.greatestFiniteMagnitude)
        textView.drawsBackground = true
        textView.backgroundColor = .textBackgroundColor
        textView.font = NSFont.preferredFont(forTextStyle: .body)
        textView.string = text

        scrollView.documentView = textView
        context.coordinator.textView = textView
        return scrollView
    }

    func updateNSView(_ nsView: NSScrollView, context: Context) {
        guard let textView = context.coordinator.textView else { return }
        if textView.string != text {
            textView.string = text
        }
        textView.backgroundColor = .textBackgroundColor
    }

    final class Coordinator: NSObject, NSTextViewDelegate {
        @Binding var text: String
        var onFocus: () -> Void
        weak var textView: BeatEditorTextView?

        init(text: Binding<String>, onFocus: @escaping () -> Void) {
            _text = text
            self.onFocus = onFocus
        }

        func textDidBeginEditing(_ notification: Notification) {
            onFocus()
        }

        func textDidChange(_ notification: Notification) {
            guard let textView else { return }
            text = textView.string
            onFocus()
        }
    }
}

private final class BeatEditorScrollView: NSScrollView {
    var onActivate: (() -> Void)?

    override func mouseDown(with event: NSEvent) {
        onActivate?()
        super.mouseDown(with: event)
    }
}

private final class BeatEditorTextView: NSTextView {
    var onActivate: (() -> Void)?

    override func becomeFirstResponder() -> Bool {
        let result = super.becomeFirstResponder()
        if result { onActivate?() }
        return result
    }

    override func mouseDown(with event: NSEvent) {
        onActivate?()
        super.mouseDown(with: event)
    }
}

private struct BeatAIDraftSheetView: View {
    @Environment(\.dismiss) private var dismiss
    @EnvironmentObject private var wizard: WizardState
    @EnvironmentObject private var ai: AIAssistant

    let beat: BeatTemplate
    let draftAction: () async -> Bool

    @State private var isDrafting = false
    @State private var errorMessage: String?

    private var label: String {
        (wizard.entries[beat.key]?.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty ?? true)
            ? "Draft with AI"
            : "Rewrite with AI"
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 18) {
            VStack(alignment: .leading, spacing: 6) {
                Text(label)
                    .font(.title2.weight(.bold))
                Text(beat.title)
                    .font(.headline)
                    .foregroundStyle(.secondary)
                Text(beat.purpose)
                    .font(.callout)
                    .foregroundStyle(.secondary)
                    .fixedSize(horizontal: false, vertical: true)
            }

            // Sample movie reference section removed in v3.0b24

            if let existing = wizard.entries[beat.key], !existing.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
                VStack(alignment: .leading, spacing: 6) {
                    Text("Current draft")
                        .font(.caption.weight(.semibold))
                        .foregroundStyle(.secondary)
                    Text(existing)
                        .font(.callout)
                        .fixedSize(horizontal: false, vertical: true)
                }
                .padding(12)
                .frame(maxWidth: .infinity, alignment: .leading)
                .background(
                    RoundedRectangle(cornerRadius: 10, style: .continuous)
                        .fill(Color(nsColor: .controlBackgroundColor)))
            }

            if let errorMessage {
                Text(errorMessage)
                    .font(.caption)
                    .foregroundStyle(.orange)
            }

            HStack {
                Button {
                    dismiss()
                } label: {
                    Text("Cancel")
                }
                .buttonStyle(.bordered)

                Spacer()

                Button {
                    Task { await startDraft() }
                } label: {
                    if isDrafting {
                        HStack(spacing: 6) {
                            ProgressView().controlSize(.small)
                            Text("Drafting…")
                        }
                    } else {
                        Label(label, systemImage: "sparkles")
                    }
                }
                .buttonStyle(.borderedProminent)
                .disabled(isDrafting || !ai.isConfigured)
            }
        }
        .padding(24)
        .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .leading)
    }

    @MainActor
    private func startDraft() async {
        isDrafting = true
        errorMessage = nil
        defer { isDrafting = false }
        if await draftAction() {
            dismiss()
        } else if !Task.isCancelled {
            errorMessage = "The AI draft could not be created. Try again after checking LM Studio."
        }
    }
}

// MARK: - BeatLineView (Inline beat editing)

struct BeatLineView: View {
    @EnvironmentObject private var wizard: WizardState
    let beat: BeatTemplate
    let isActive: Bool
    let onFocus: () -> Void

    private var binding: Binding<String> {
        Binding(
            get: { wizard.entries[beat.key] ?? "" },
            set: { wizard.entries[beat.key] = $0 }
        )
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            HStack(alignment: .firstTextBaseline) {
                Text(beat.title)
                    .font(.headline.weight(.bold))
                if isActive {
                    Text("Editing")
                        .font(.caption.weight(.semibold))
                        .padding(.horizontal, 8)
                        .padding(.vertical, 3)
                        .background(Capsule().fill(Color.accentColor.opacity(0.14)))
                        .foregroundStyle(.tint)
                }
                Spacer()
                if let runtime = wizard.runtime {
                    Text(beat.timing(for: runtime))
                        .font(.caption.weight(.medium))
                        .foregroundStyle(.secondary)
                        .padding(.horizontal, 8)
                        .padding(.vertical, 3)
                        .background(Capsule().fill(Color.secondary.opacity(0.12)))
                }
            }

            ZStack(alignment: .topLeading) {
                BeatDraftTextEditor(text: binding) {
                    onFocus()
                }
                .frame(minHeight: 80)
                .background(
                    RoundedRectangle(cornerRadius: 10)
                        .fill(isActive ? Color.accentColor.opacity(0.06) : Color(nsColor: .textBackgroundColor)))
                .overlay(
                    RoundedRectangle(cornerRadius: 10)
                        .strokeBorder(isActive ? Color.accentColor.opacity(0.35) : Color.primary.opacity(0.12), lineWidth: isActive ? 1.5 : 1))
                .onChange(of: binding.wrappedValue) { _, _ in onFocus() }
            }

            Text(beat.purpose)
                .font(.callout)
                .foregroundStyle(.secondary)
                .fixedSize(horizontal: false, vertical: true)
        }
        .padding(16)
        .background(
            RoundedRectangle(cornerRadius: 12, style: .continuous)
                .fill(Color(nsColor: .controlBackgroundColor)))
        .overlay(
            RoundedRectangle(cornerRadius: 12, style: .continuous)
                .strokeBorder(isActive ? Color.accentColor.opacity(0.3) : Color.primary.opacity(0.08), lineWidth: isActive ? 2 : 1))
        .contentShape(RoundedRectangle(cornerRadius: 12, style: .continuous))
        .onTapGesture {
            onFocus()
        }
    }
}
