import SwiftUI
import AppKit
import UniformTypeIdentifiers

struct TemplateStepView: View {
    @EnvironmentObject private var wizard: WizardState
    @EnvironmentObject private var ai: AIAssistant
    @State private var showCopiedToast = false
    @State private var assistantPrompt = ""
    @State private var assistantPromptSourceBeatKey: String?
    @State private var assistantPromptIsAutoGenerated = true
    @State private var assistantSuggestion: String?
    @State private var assistantSuggestionBeatKey: String?
    @State private var isPrompting = false
    @State private var selectedBeatKey: String = ""
    @State private var beatElement: BeatElement = .section
    @State private var includeGuidance = true

    private var filledCount: Int {
        wizard.beats.filter { !(wizard.entries[$0.key]?.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty ?? true) }.count
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 24) {
            heading
            assistantPromptPanel
            progressBar

            ForEach(actGroups, id: \.act) { group in
                VStack(alignment: .leading, spacing: 14) {
                    Text(group.label)
                        .font(.title3.weight(.bold))
                        .foregroundStyle(.tint)
                        .padding(.top, 4)
                    ForEach(group.beats) { beat in
                        BeatCardView(
                            beat: beat,
                            isTargeted: selectedBeatKey == beat.key,
                            inlineSuggestion: assistantSuggestionBeatKey == beat.key ? assistantSuggestion : nil,
                            onFocus: { selectedBeatKey = beat.key }
                        )
                    }
                }
            }
        }
        .overlay(alignment: .bottom) {
            if showCopiedToast {
                Text("Outline copied to clipboard")
                    .font(.callout.weight(.medium))
                    .padding(.horizontal, 16)
                    .padding(.vertical, 10)
                    .background(Capsule().fill(.black.opacity(0.8)))
                    .foregroundStyle(.white)
                    .transition(.move(edge: .bottom).combined(with: .opacity))
                    .padding(.bottom, 8)
            }
        }
        .onAppear { syncSelectedBeat() }
        .onChange(of: wizard.beats.map(\.key)) { _, _ in syncSelectedBeat() }
        .onChange(of: selectedBeatKey) { _, _ in syncAssistantPrompt() }
        .onChange(of: assistantPrompt) { _, newValue in
            guard let beat = selectedBeat else {
                assistantPromptIsAutoGenerated = false
                assistantPromptSourceBeatKey = nil
                return
            }
            let generated = autoPrompt(for: beat)
            if newValue == generated {
                assistantPromptIsAutoGenerated = true
                assistantPromptSourceBeatKey = beat.key
            } else {
                assistantPromptIsAutoGenerated = false
            }
        }
    }

    // MARK: Heading

    private var heading: some View {
        VStack(alignment: .leading, spacing: 16) {
            HStack(alignment: .top) {
                VStack(alignment: .leading, spacing: 6) {
                    Text("YOUR TEMPLATE")
                        .font(.caption.weight(.semibold))
                        .foregroundStyle(.tint)
                        .tracking(1.2)
                    Text(wizard.projectTitle.isEmpty ? "Untitled" : wizard.projectTitle)
                        .font(.system(size: 30, weight: .bold, design: .rounded))
                    metaLine
                }
                Spacer()
                HStack(spacing: 10) {
                    Button {
                        copyToClipboard()
                    } label: {
                        Label("Copy", systemImage: "doc.on.doc")
                    }
                    Button {
                        exportToFile()
                    } label: {
                        Label("Export…", systemImage: "square.and.arrow.up")
                    }
                    Menu {
                        Picker("Beat style", selection: $beatElement) {
                            ForEach(BeatElement.allCases) { element in
                                Text(element.label).tag(element)
                            }
                        }
                        .pickerStyle(.inline)
                        Divider()
                        Toggle("Include guidance & references", isOn: $includeGuidance)
                        Divider()
                        Button {
                            exportFDX()
                        } label: {
                            Label("Save .fdx…", systemImage: "square.and.arrow.down")
                        }
                    } label: {
                        Label("Final Draft…", systemImage: "film.stack")
                    } primaryAction: {
                        exportFDX()
                    }
                    .menuStyle(.borderlessButton)
                    .buttonStyle(.borderedProminent)
                    .fixedSize()
                }
            }
            if !wizard.logline.isEmpty {
                Text(wizard.logline)
                    .font(.title3)
                    .italic()
                    .foregroundStyle(.secondary)
            }
        }
    }

    private var metaLine: some View {
        HStack(spacing: 6) {
            if let s = wizard.structure { Text(s.title) }
            if let m = wizard.medium, let r = wizard.runtime {
                Text("·"); Text("\(m.rawValue) · \(r.label)")
            }
            if let g = wizard.genre { Text("·"); Text(g.title) }
            if let movie = wizard.sampleMovie { Text("· styled after"); Text(movie.title).fontWeight(.semibold) }
        }
        .font(.callout)
        .foregroundStyle(.secondary)
    }

    private var assistantPromptPanel: some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack(alignment: .firstTextBaseline) {
                VStack(alignment: .leading, spacing: 4) {
                    Text("AI Assistant")
                        .font(.headline)
                    Text("Choose a beat, then ask for a draft, rewrite, or notes.")
                        .font(.callout)
                        .foregroundStyle(.secondary)
                }
                Spacer()
                if !ai.isConfigured {
                    Text("Connect a local LLM in the AI menu")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }
            }

            if let beat = selectedBeat {
                HStack(spacing: 8) {
                    Image(systemName: "target")
                        .font(.caption.weight(.semibold))
                    Text("Targeting")
                        .font(.caption.weight(.semibold))
                    Text(beat.title)
                        .font(.caption)
                    Spacer()
                    Text(beat.actLabel)
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }
                .padding(.horizontal, 12)
                .padding(.vertical, 8)
                .background(
                    RoundedRectangle(cornerRadius: 10, style: .continuous)
                        .fill(Color.accentColor.opacity(0.08)))
            }

            Picker("Target beat", selection: selectedBeatSelection) {
                ForEach(wizard.beats) { beat in
                    Text(beat.title).tag(beat.key)
                }
            }
            .pickerStyle(.menu)

            ZStack(alignment: .topLeading) {
                TextEditor(text: $assistantPrompt)
                    .font(.body)
                    .frame(minHeight: 88)
                    .padding(8)
                    .background(
                        RoundedRectangle(cornerRadius: 10)
                            .fill(Color(nsColor: .textBackgroundColor)))
                    .overlay(
                        RoundedRectangle(cornerRadius: 10)
                            .strokeBorder(Color.primary.opacity(0.1)))
                if assistantPrompt.isEmpty {
                    Text("Ask something like: \"How can I raise the stakes in the midpoint?\"")
                        .foregroundStyle(.secondary)
                        .padding(16)
                        .allowsHitTesting(false)
                }
            }

            HStack(spacing: 10) {
                Button {
                    Task { await askAssistant() }
                } label: {
                    if isPrompting {
                        HStack(spacing: 6) {
                            ProgressView().controlSize(.small)
                            Text("Asking…")
                        }
                    } else {
                        Label("Ask AI", systemImage: "sparkles")
                    }
                }
                .buttonStyle(.borderedProminent)
                .disabled(isPrompting || assistantPrompt.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty || !ai.isConfigured || selectedBeat == nil)

                Button("Clear") {
                    assistantPrompt = ""
                    clearSuggestion()
                }
                .disabled(isPrompting)

                Spacer()
            }

            if let assistantSuggestion,
               let suggestionBeat = selectedBeat,
               assistantSuggestionBeatKey == suggestionBeat.key {
                VStack(alignment: .leading, spacing: 10) {
                    HStack {
                        Text("AI suggestion")
                            .font(.headline)
                        Spacer()
                        Text(suggestionBeat.title)
                            .font(.caption)
                            .foregroundStyle(.secondary)
                        Button {
                            copyToClipboard(assistantSuggestion)
                        } label: {
                            Label("Copy", systemImage: "doc.on.doc")
                        }
                        .buttonStyle(.borderless)
                    }

                    Text(assistantSuggestion)
                        .font(.callout)
                        .fixedSize(horizontal: false, vertical: true)
                        .textSelection(.enabled)

                    HStack {
                        Button {
                            useSuggestion()
                        } label: {
                            Label("Use suggestion", systemImage: "arrow.down.doc")
                        }
                        .buttonStyle(.borderedProminent)

                        Button("Dismiss") {
                            clearSuggestion()
                        }
                        .buttonStyle(.bordered)

                        Spacer()
                    }
                }
                .padding(14)
                .frame(maxWidth: .infinity, alignment: .leading)
                .background(
                    RoundedRectangle(cornerRadius: 12, style: .continuous)
                        .fill(Color(nsColor: .controlBackgroundColor)))
                .overlay(
                    RoundedRectangle(cornerRadius: 12, style: .continuous)
                        .strokeBorder(Color.primary.opacity(0.08)))
            }
        }
        .padding(18)
        .background(
            RoundedRectangle(cornerRadius: 14, style: .continuous)
                .fill(Color(nsColor: .controlBackgroundColor)))
        .overlay(
            RoundedRectangle(cornerRadius: 14, style: .continuous)
                .strokeBorder(Color.primary.opacity(0.08)))
    }

    private var progressBar: some View {
        VStack(alignment: .leading, spacing: 6) {
            HStack {
                Text("\(filledCount) of \(wizard.beats.count) beats written")
                    .font(.caption.weight(.medium))
                    .foregroundStyle(.secondary)
                Spacer()
            }
            GeometryReader { geo in
                ZStack(alignment: .leading) {
                    Capsule().fill(Color.secondary.opacity(0.18))
                    Capsule().fill(Color.accentColor)
                        .frame(width: geo.size.width * progressFraction)
                }
            }
            .frame(height: 8)
        }
    }

    private var progressFraction: CGFloat {
        guard !wizard.beats.isEmpty else { return 0 }
        return CGFloat(filledCount) / CGFloat(wizard.beats.count)
    }

    // MARK: Grouping

    private struct ActGroup { let act: Int; let label: String; let beats: [BeatTemplate] }

    private var actGroups: [ActGroup] {
        var groups: [ActGroup] = []
        for beat in wizard.beats {
            if let idx = groups.firstIndex(where: { $0.act == beat.act }) {
                groups[idx] = ActGroup(act: beat.act, label: groups[idx].label, beats: groups[idx].beats + [beat])
            } else {
                groups.append(ActGroup(act: beat.act, label: beat.actLabel, beats: [beat]))
            }
        }
        return groups
    }

    // MARK: Actions

    private func copyToClipboard() {
        let pb = NSPasteboard.general
        pb.clearContents()
        pb.setString(wizard.exportText(), forType: .string)
        withAnimation { showCopiedToast = true }
        DispatchQueue.main.asyncAfter(deadline: .now() + 1.8) {
            withAnimation { showCopiedToast = false }
        }
    }

    private func exportToFile() {
        let panel = NSSavePanel()
        panel.allowedContentTypes = [.plainText]
        let safeTitle = wizard.projectTitle.isEmpty ? "CreateIT Outline" : wizard.projectTitle
        panel.nameFieldStringValue = "\(safeTitle).txt"
        panel.canCreateDirectories = true
        if panel.runModal() == .OK, let url = panel.url {
            try? wizard.exportText().write(to: url, atomically: true, encoding: .utf8)
        }
    }

    private func exportFDX() {
        let panel = NSSavePanel()
        if let fdxType = UTType(filenameExtension: "fdx") {
            panel.allowedContentTypes = [fdxType]
        }
        let safeTitle = wizard.projectTitle.isEmpty ? "CreateIT" : wizard.projectTitle
        panel.nameFieldStringValue = "\(safeTitle).fdx"
        panel.canCreateDirectories = true
        if panel.runModal() == .OK, let url = panel.url {
            let fdx = FDXExporter.export(from: wizard, beatElement: beatElement, includeGuidance: includeGuidance)
            try? fdx.write(to: url, atomically: true, encoding: .utf8)
        }
    }

    private func copyToClipboard(_ text: String) {
        let pb = NSPasteboard.general
        pb.clearContents()
        pb.setString(text, forType: .string)
    }

    @MainActor
    private func askAssistant() async {
        let prompt = assistantPrompt.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !prompt.isEmpty else { return }
        guard let beat = selectedBeat else { return }
        isPrompting = true
        defer { isPrompting = false }

        if let result = await ai.answerPrompt(prompt, beat: beat, wizard: wizard) {
            assistantSuggestion = result
            assistantSuggestionBeatKey = beat.key
        }
    }

    private var selectedBeat: BeatTemplate? {
        wizard.beats.first(where: { $0.key == selectedBeatKey }) ?? wizard.beats.first
    }

    private var selectedBeatSelection: Binding<String> {
        Binding(
            get: { selectedBeatKey.isEmpty ? (wizard.beats.first?.key ?? "") : selectedBeatKey },
            set: { selectedBeatKey = $0 }
        )
    }

    private func syncSelectedBeat() {
        guard let first = wizard.beats.first else {
            selectedBeatKey = ""
            return
        }
        if wizard.beats.contains(where: { $0.key == selectedBeatKey }) {
            syncAssistantPrompt()
            return
        }
        selectedBeatKey = first.key
    }

    private func syncAssistantPrompt() {
        guard let beat = selectedBeat else {
            assistantPrompt = ""
            assistantPromptSourceBeatKey = nil
            assistantPromptIsAutoGenerated = true
            clearSuggestion()
            return
        }

        let generated = autoPrompt(for: beat)
        if assistantPrompt.isEmpty || assistantPromptIsAutoGenerated || assistantPromptSourceBeatKey != beat.key {
            assistantPrompt = generated
            assistantPromptSourceBeatKey = beat.key
            assistantPromptIsAutoGenerated = true
            clearSuggestion()
        }
    }

    private func autoPrompt(for beat: BeatTemplate) -> String {
        let draft = currentDraftText(for: beat)
        let draftAction = draft.isEmpty
            ? "Draft this beat from scratch."
            : "Rewrite this beat to make it sharper and more dramatic."
        let timing = wizard.runtime.map { beat.timing(for: $0) } ?? "Unknown"

        return """
        Beat Brief
        Title: \(beat.title)
        Act: \(beat.actLabel)
        Timing: \(timing)

        Purpose:
        \(beat.purpose)

        Current Draft:
        \(draft.isEmpty ? "No draft yet." : draft)

        Request:
        \(draftAction)
        """
    }

    private func currentDraftText(for beat: BeatTemplate) -> String {
        wizard.entries[beat.key]?
            .trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
    }

    private func useSuggestion() {
        guard let beat = selectedBeat, let assistantSuggestion else { return }
        let current = currentDraftText(for: beat)
        let merged = mergeDraft(current: current, suggestion: assistantSuggestion)
        wizard.entries[beat.key] = merged
        clearSuggestion()
        syncAssistantPrompt()
    }

    private func mergeDraft(current: String, suggestion: String) -> String {
        let currentSentences = sentenceList(from: current)
        let suggestionSentences = sentenceList(from: suggestion)

        guard !currentSentences.isEmpty else { return suggestion.trimmingCharacters(in: .whitespacesAndNewlines) }
        guard !suggestionSentences.isEmpty else { return current.trimmingCharacters(in: .whitespacesAndNewlines) }

        let count = max(currentSentences.count, suggestionSentences.count)
        var merged: [String] = []
        for index in 0..<count {
            let original = index < currentSentences.count ? currentSentences[index] : nil
            let rewritten = index < suggestionSentences.count ? suggestionSentences[index] : nil

            switch (original, rewritten) {
            case let (_, rewritten?):
                merged.append(rewritten)
            case let (original?, nil):
                merged.append(original)
            case (nil, nil):
                break
            }
        }
        return merged.joined(separator: " ")
    }

    private func sentenceList(from text: String) -> [String] {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return [] }

        let nsText = trimmed as NSString
        var sentences: [String] = []
        nsText.enumerateSubstrings(
            in: NSRange(location: 0, length: nsText.length),
            options: [.bySentences, .substringNotRequired]
        ) { _, range, _, _ in
            let sentence = nsText.substring(with: range).trimmingCharacters(in: .whitespacesAndNewlines)
            if !sentence.isEmpty {
                sentences.append(sentence)
            }
        }
        return sentences.isEmpty ? [trimmed] : sentences
    }

    private func clearSuggestion() {
        assistantSuggestion = nil
        assistantSuggestionBeatKey = nil
    }
}

// MARK: - Beat Card

struct BeatCardView: View {
    @EnvironmentObject private var wizard: WizardState
    @EnvironmentObject private var ai: AIAssistant
    let beat: BeatTemplate
    let isTargeted: Bool
    let inlineSuggestion: String?
    let onFocus: () -> Void
    @State private var showSample = true

    private var isGenerating: Bool { ai.generating.contains(beat.key) }

    private var binding: Binding<String> {
        Binding(
            get: { wizard.entries[beat.key] ?? "" },
            set: { wizard.entries[beat.key] = $0 }
        )
    }

    private var sampleText: String? {
        wizard.sampleMovie?.sample(for: beat.key)
    }

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            header
            Text(beat.purpose)
                .font(.callout)
                .foregroundStyle(.secondary)
                .fixedSize(horizontal: false, vertical: true)

            if let sampleText {
                sampleBox(sampleText)
            }

            ZStack(alignment: .topLeading) {
                TextEditor(text: binding)
                    .font(.body)
                    .frame(minHeight: 90)
                    .padding(8)
                    .background(
                        RoundedRectangle(cornerRadius: 10)
                            .fill(Color(nsColor: .textBackgroundColor)))
                    .overlay(
                        RoundedRectangle(cornerRadius: 10)
                            .strokeBorder(Color.primary.opacity(0.1)))
                    .onTapGesture { onFocus() }
                    .onChange(of: binding.wrappedValue) { _, _ in onFocus() }
                if binding.wrappedValue.isEmpty {
                    Text(beat.placeholder)
                        .foregroundStyle(.secondary)
                        .padding(16)
                        .allowsHitTesting(false)
                }
            }

            if let inlineSuggestion, isTargeted {
                suggestionBox(inlineSuggestion)
            }

            aiToolbar
        }
        .padding(18)
        .background(
            RoundedRectangle(cornerRadius: 14, style: .continuous)
                .fill(isTargeted ? Color.accentColor.opacity(0.10) : Color(nsColor: .controlBackgroundColor)))
        .overlay(
            RoundedRectangle(cornerRadius: 14, style: .continuous)
                .strokeBorder(isTargeted ? Color.accentColor : Color.primary.opacity(0.08), lineWidth: isTargeted ? 2 : 1))
    }

    @ViewBuilder
    private var aiToolbar: some View {
        HStack(spacing: 10) {
            Button {
                Task { await draftWithAI() }
            } label: {
                if isGenerating {
                    HStack(spacing: 6) {
                        ProgressView().controlSize(.small)
                        Text("Writing…")
                    }
                } else {
                    Label(binding.wrappedValue.isEmpty ? "Draft with AI" : "Rewrite with AI",
                          systemImage: "sparkles")
                }
            }
            .disabled(isGenerating || !ai.isConfigured)
            .controlSize(.small)

            if !ai.isConfigured {
                Text("Connect a local LLM in the AI menu")
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }
            Spacer()
        }
    }

    private var header: some View {
        HStack(alignment: .firstTextBaseline) {
            Text(beat.title)
                .font(.title3.weight(.bold))
            if isTargeted {
                Text("AI target")
                    .font(.caption.weight(.semibold))
                    .padding(.horizontal, 8)
                    .padding(.vertical, 3)
                    .background(Capsule().fill(Color.accentColor.opacity(0.14)))
                    .foregroundStyle(.tint)
            }
            Spacer()
            if let runtime = wizard.runtime {
                Text(beat.timing(for: runtime))
                    .font(.caption.weight(.medium))
                    .foregroundStyle(.secondary)
                    .padding(.horizontal, 8)
                    .padding(.vertical, 3)
                    .background(Capsule().fill(Color.secondary.opacity(0.12)))
            }
        }
        .onAppear(perform: onFocus)
    }

    private func suggestionBox(_ text: String) -> some View {
        let current = binding.wrappedValue
        let previewRows = sentencePreviewRows(current: current, suggestion: text)

        return VStack(alignment: .leading, spacing: 8) {
            HStack {
                Label("AI suggestion", systemImage: "sparkles")
                    .font(.caption.weight(.semibold))
                    .foregroundStyle(.tint)
                Spacer()
                Text("Review before applying")
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }

            Text(text)
                .font(.callout)
                .fixedSize(horizontal: false, vertical: true)
                .textSelection(.enabled)

            if !previewRows.isEmpty {
                VStack(alignment: .leading, spacing: 8) {
                    HStack {
                        Text("Merge preview")
                            .font(.caption.weight(.semibold))
                            .foregroundStyle(.secondary)
                        Spacer()
                        Text("\(previewRows.filter { $0.kind != .kept }.count) changes")
                            .font(.caption)
                            .foregroundStyle(.secondary)
                    }

                    VStack(alignment: .leading, spacing: 8) {
                        ForEach(Array(previewRows.enumerated()), id: \.offset) { _, row in
                            sentencePreviewRow(row)
                        }
                    }
                    .padding(10)
                    .background(
                        RoundedRectangle(cornerRadius: 8, style: .continuous)
                            .fill(Color(nsColor: .windowBackgroundColor).opacity(0.65)))
                }
            }
        }
        .padding(12)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(
            RoundedRectangle(cornerRadius: 10, style: .continuous)
                .fill(Color.accentColor.opacity(0.08)))
        .overlay(
            RoundedRectangle(cornerRadius: 10, style: .continuous)
                .strokeBorder(Color.accentColor.opacity(0.18)))
    }

    private enum SentencePreviewKind {
        case kept
        case replaced
        case added
    }

    private struct SentencePreviewRow {
        let kind: SentencePreviewKind
        let current: String?
        let suggestion: String?
    }

    @ViewBuilder
    private func sentencePreviewRow(_ row: SentencePreviewRow) -> some View {
        HStack(alignment: .top, spacing: 8) {
            Text(label(for: row.kind))
                .font(.caption2.weight(.semibold))
                .foregroundStyle(color(for: row.kind))
                .frame(width: 58, alignment: .leading)

            VStack(alignment: .leading, spacing: 4) {
                if let current = row.current, row.kind != .added {
                    Text(current)
                        .font(.caption)
                        .foregroundStyle(row.kind == .kept ? Color.secondary : Color.secondary.opacity(0.8))
                        .strikethrough(row.kind == .replaced, color: .secondary)
                }
                if let suggestion = row.suggestion, row.kind != .kept {
                    Text(suggestion)
                        .font(.caption)
                        .foregroundStyle(row.kind == .added ? .green : .primary)
                }
            }

            Spacer(minLength: 0)
        }
        .padding(.vertical, 2)
    }

    private func label(for kind: SentencePreviewKind) -> String {
        switch kind {
        case .kept: return "KEEP"
        case .replaced: return "REPLACE"
        case .added: return "ADD"
        }
    }

    private func color(for kind: SentencePreviewKind) -> Color {
        switch kind {
        case .kept: return .secondary
        case .replaced: return .orange
        case .added: return .green
        }
    }

    private func sentencePreviewRows(current: String, suggestion: String) -> [SentencePreviewRow] {
        let currentSentences = sentenceList(from: current)
        let suggestionSentences = sentenceList(from: suggestion)

        guard !currentSentences.isEmpty else {
            return suggestionSentences.map {
                SentencePreviewRow(kind: .added, current: nil, suggestion: $0)
            }
        }

        guard !suggestionSentences.isEmpty else {
            return currentSentences.map {
                SentencePreviewRow(kind: .kept, current: $0, suggestion: nil)
            }
        }

        let count = max(currentSentences.count, suggestionSentences.count)
        var rows: [SentencePreviewRow] = []
        for index in 0..<count {
            let original = index < currentSentences.count ? currentSentences[index] : nil
            let rewritten = index < suggestionSentences.count ? suggestionSentences[index] : nil

            switch (original, rewritten) {
            case let (original?, rewritten?):
                if original == rewritten {
                    rows.append(SentencePreviewRow(kind: .kept, current: original, suggestion: nil))
                } else {
                    rows.append(SentencePreviewRow(kind: .replaced, current: original, suggestion: rewritten))
                }
            case let (original?, _):
                rows.append(SentencePreviewRow(kind: .kept, current: original, suggestion: nil))
            case let (nil, rewritten?):
                rows.append(SentencePreviewRow(kind: .added, current: nil, suggestion: rewritten))
            case (nil, nil):
                break
            }
        }
        return rows
    }

    private func sentenceList(from text: String) -> [String] {
        let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return [] }

        let nsText = trimmed as NSString
        var sentences: [String] = []
        nsText.enumerateSubstrings(
            in: NSRange(location: 0, length: nsText.length),
            options: [.bySentences, .substringNotRequired]
        ) { _, range, _, _ in
            let sentence = nsText.substring(with: range).trimmingCharacters(in: .whitespacesAndNewlines)
            if !sentence.isEmpty {
                sentences.append(sentence)
            }
        }
        return sentences.isEmpty ? [trimmed] : sentences
    }

    private func sampleBox(_ text: String) -> some View {
        VStack(alignment: .leading, spacing: 4) {
            HStack(spacing: 6) {
                Image(systemName: "lightbulb")
                    .font(.caption)
                Text("How \(wizard.sampleMovie?.title ?? "the sample") handles this beat")
                    .font(.caption.weight(.semibold))
                Spacer()
                Button(showSample ? "Hide" : "Show") {
                    withAnimation { showSample.toggle() }
                }
                .buttonStyle(.plain)
                .font(.caption)
                .foregroundStyle(.tint)
            }
            .foregroundStyle(.tint)

            if showSample {
                Text(text)
                    .font(.callout)
                    .italic()
                    .fixedSize(horizontal: false, vertical: true)
                    .foregroundStyle(.primary.opacity(0.85))
            }
        }
        .padding(12)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(
            RoundedRectangle(cornerRadius: 10)
                .fill(Color.accentColor.opacity(0.08)))
        .overlay(
            RoundedRectangle(cornerRadius: 10)
                .strokeBorder(Color.accentColor.opacity(0.2)))
    }

    @MainActor
    private func draftWithAI() async {
        if let result = await ai.draftBeat(beat, wizard: wizard) {
            wizard.entries[beat.key] = result
        }
    }
}
